package az.coder.task1.ExceptionTryCatchTest;

public class Main {

    public static void main(String[] args) throws StudentException {
        System.out.println(Student.find("123"));
    }
}
